<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF37ibga\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF37ibga/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerF37ibga.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerF37ibga\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerF37ibga\appProdProjectContainer([
    'container.build_hash' => 'F37ibga',
    'container.build_id' => 'f131e69e',
    'container.build_time' => 1605444192,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF37ibga');
