<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUcyjyzf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUcyjyzf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUcyjyzf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUcyjyzf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUcyjyzf\appProdProjectContainer([
    'container.build_hash' => 'Ucyjyzf',
    'container.build_id' => 'cd901290',
    'container.build_time' => 1604761148,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUcyjyzf');
