<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcv2aer\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcv2aer/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBcv2aer.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBcv2aer\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBcv2aer\appProdProjectContainer([
    'container.build_hash' => 'Bcv2aer',
    'container.build_id' => '17bdf4df',
    'container.build_time' => 1606079723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcv2aer');
