<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP9k0evj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP9k0evj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerP9k0evj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP9k0evj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerP9k0evj\appDevDebugProjectContainer([
    'container.build_hash' => 'P9k0evj',
    'container.build_id' => 'd82ecf60',
    'container.build_time' => 1607617690,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP9k0evj');
