<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQb0bpyq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQb0bpyq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQb0bpyq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQb0bpyq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQb0bpyq\appDevDebugProjectContainer([
    'container.build_hash' => 'Qb0bpyq',
    'container.build_id' => '2adb940e',
    'container.build_time' => 1607104299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQb0bpyq');
